Repository AZMAG/FMS, pull requests merged in 2022-10, with the labels that each got.

#37 Compare updates
  client/package-lock.json
  client/package.json
  client/src/components/GeneratedReport/GeneratedReportLink.js
  client/src/components/GeneratedReport/MainGeneratedReport.js
  client/src/components/Layout/footer/Footer.js
  client/src/components/Layout/header/Nav.js
  client/src/components/Layout/pages/Detector.js
  client/src/components/Layout/pages/GeneratedReports.js
  client/src/components/Layout/pages/Home.js
  client/src/components/Layout/pages/ReportBuilder.js
  client/src/components/Layout/pages/pages.css
  client/src/components/Map/getDetectorsLayer.js
  client/src/components/MapWidgets/mapWidgets.css
  client/src/components/Modals/legal/LegalModal.js
  client/src/components/Modals/privacy/PrivacyModal.js
  client/src/components/Modals/terms/TermsModal.js
  client/src/components/ReportBuilder/AnalysisCheckboxGrid.js
  client/src/components/ReportBuilder/DetectorDropdown.js
  client/src/components/ReportBuilder/TimePeriodSelection.js
  client/src/components/ScrollToTop/scrollToTop.css
  client/src/components/ScrollToTop/scrollToTop.js
Labels: Experience: design, Experience: ux

#43 Reports generated updates
  client/src/components/GeneratedReport/GeneratedReportLink.js
  client/src/components/Layout/pages/GeneratedReports.js
  client/src/components/Layout/pages/GeneratedReports_mu.js
  client/src/components/Layout/pages/pages.css
  client/src/components/Modals/legal/LegalModal.js
  client/src/components/Modals/modal.css
  client/src/components/Modals/privacy/PrivacyModal.js
  client/src/components/Modals/terms/TermsModal.js
Labels: Experience: design

#42 Fix data structure
  client/src/components/Map/getDetectorsLayer.js
  server/FMS Dashboard/Models/DataModel.Context.cs
  server/FMS Dashboard/Models/DataModel.edmx
  server/FMS Dashboard/Models/DataModel.edmx.diagram
  server/FMS Dashboard/Models/detector_Validity.cs
Labels: Experience: database
